# Generated by Django 5.1.1 on 2024-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_you',
            field=models.BooleanField(default=False),
        ),
    ]
